### ISSUE TITLE
About Text Extraction

### ISSUE THREAD

**Issue by Kitcham** [psthrn42/SCVI_Extract#6]
Hi~
I am using the great tool (already updated to the PR ver.) to extract some text recourses. And It seems that all text files extracted in `messagedat` are binary type files. So, I'd like to know how I can get the correct text file? THX!

**Comment by bWFpbA** [comment]
That is just how text is stored in Pokemon games. The format used in SV has been in use since XY.
I don't know if a better tool exists, but Kaphotic's old [xytext](https://github.com/kwsch/xytext) should handle them just fine.

**Comment by FullLifeGames** [comment]
@Kitcham I used https://github.com/CMahk/read_swsh to extract text.

Identify the text you want to extract and then which of these files is the .tbl and which the .dat file. Name them accordingly. Then execute like below:

Example usage: `python .\read_swsh.py "output\arc\messagedat\English\common\competition_organize.tbl\0x6b657873c4ca07f5.tbl" "output\arc\messagedat\English\common\competition_organize.tbl\0xe1aade7377061c3e.dat"`

**Comment by Kitcham** [comment]
@bWFpbA @FullLifeGames Thanks a lot！

I referred to both repositories CMahk's [read_swsh](https://github.com/CMahk/read_swsh) and Kaphotic's [xytext](https://github.com/kwsch/xytext) to figure out what kind of text format this is. Now I have successfully extracted the file I want.
